name: 'flakybot'
author: 'Justin Beckwith'
description: 'The Flaky Bot manages issues for failing tests.'
branding:
  icon: 'link'
  color: 'purple'
inputs:
  xunitPath:
    description: 'Path to the xunit formatted test output.'
    default: 'output.xml'
    required: false
  labels:
    description: 'List of labels to apply to the issue.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
